### ISSUE TITLE
Update the npm install command

### ISSUE THREAD

**Issue by mojavelinux** [man-chi/example-antora-basic#1]
Instead of this:

```
npm install -g asciidoctor asciidoctor-kroki @antora/cli @antora/site-generator @antora/lunr-extension
```

The install command should be:

```
npm install antora asciidoctor-kroki @antora/lunr-extension
```

There's no reason to install the modules globally. The Antora package should be consolidated to `antora`. There's also no reason to install the asciidoctor package as that is already included with Antora and the version installed independently will be incorrect.

**Comment by man-chi** [comment]
thanks for the comment, let me fix this today

**Comment by man-chi** [comment]
> Instead of this:
> 
> ```
> npm install -g asciidoctor asciidoctor-kroki @antora/cli @antora/site-generator @antora/lunr-extension
> ```
> 
> The install command should be:
> 
> ```
> npm install antora asciidoctor-kroki @antora/lunr-extension
> ```
> 
> There's no reason to install the modules globally. The Antora package should be consolidated to `antora`. There's also no reason to install the asciidoctor package as that is already included with Antora and the version installed independently will be incorrect.

fixed in the new push.

**Comment by mojavelinux** [comment]
Excellent news!
